[package]
name = "bindingtester"
version = "0.6.0"
authors = [
    "Benjamin Fry <benjaminfry@me.com>",
    "Vincent Rouill√© <vincent@clikengo.com>",
    "Pierre Zemb <contact@pierrezemb.fr>"
]
edition = "2021"
rust-version = "1.56"

description = """
Bindings to the C api for FoundationDB
"""

repository = "https://github.com/foundationdb-rs/foundationdb-rs"

readme = "README.md"
keywords = ["foundationdb", "kv"]
categories = ["database"]

license = "MIT/Apache-2.0"

[dependencies]
env_logger = "0.9.0"
foundationdb = { path = "../foundationdb", features = ["uuid", "num-bigint", "fdb-7_1"], default-features = false }
foundationdb-sys = { version = "0.6.0", path = "../foundationdb-sys", default-features = false }
futures = "0.3.21"
log = "0.4.17"
num-bigint = "0.4.3"
structopt = "0.3.26"
async-trait = "0.1.56"
